-- MySQL Script generated by MySQL Workbench
-- Mon Jan 16 02:25:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `id_number` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `member_since` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car_brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car_brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `country_of_origin` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand_models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand_models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `car_brand_id` INT NOT NULL,
  `fuel_type` VARCHAR(100) NOT NULL,
  `transmission` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Brand_Models_Car_brands1_idx` (`car_brand_id` ASC),
  CONSTRAINT `fk_Brand_Models_Car_brands1`
    FOREIGN KEY (`car_brand_id`)
    REFERENCES `mydb`.`Car_brands` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` DATE NOT NULL,
  `user_id` INT NOT NULL,
  `car_brand_id` INT NOT NULL,
  `brand_model_id` INT NOT NULL,
  `license_plate` VARCHAR(100) NOT NULL,
  `current_mileage` VARCHAR(100) NOT NULL,
  `color` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cars_users_idx` (`user_id` ASC),
  INDEX `fk_Cars_Car_brands1_idx` (`car_brand_id` ASC),
  INDEX `fk_Cars_Brand_Models1_idx` (`brand_model_id` ASC),
  CONSTRAINT `fk_cars_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_Car_brands1`
    FOREIGN KEY (`car_brand_id`)
    REFERENCES `mydb`.`Car_brands` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cars_Brand_Models1`
    FOREIGN KEY (`brand_model_id`)
    REFERENCES `mydb`.`Brand_models` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car_part_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car_part_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shops` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car_parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car_parts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `serial_number` VARCHAR(100) NOT NULL,
  `price` DECIMAL(9) NOT NULL,
  `car_part_category_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Car_Parts_Car_part_categories1_idx` (`car_part_category_id` ASC),
  INDEX `fk_Car_Parts_Shops1_idx` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `fk_Car_Parts_Car_part_categories1`
    FOREIGN KEY (`car_part_category_id`)
    REFERENCES `mydb`.`Car_part_categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Car_Parts_Shops1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`Shops` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service_stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service_stations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shop_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shop_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `shop_id` INT NOT NULL,
  `car_parts_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `order_status` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_has_Shops_Shops1_idx` (`shop_id` ASC),
  INDEX `fk_Users_has_Shops_Users1_idx` (`user_id` ASC),
  INDEX `fk_Shop_Orders_Car_Parts1_idx` (`car_parts_id` ASC),
  CONSTRAINT `fk_Users_has_Shops_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Shops_Shops1`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`Shops` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shop_Orders_Car_Parts1`
    FOREIGN KEY (`car_parts_id`)
    REFERENCES `mydb`.`Car_parts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car_services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL(9) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_station_id` INT NOT NULL,
  `car_id` INT NOT NULL,
  `car_services_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `service_status` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Service_Stations_has_Cars_Cars1_idx` (`car_id` ASC),
  INDEX `fk_Service_Stations_has_Cars_Service_Stations1_idx` (`service_station_id` ASC),
  INDEX `fk_Service_Orders_Car_Services1_idx` (`car_services_id` ASC),
  INDEX `fk_Service_orders_Users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Service_Stations_has_Cars_Service_Stations1`
    FOREIGN KEY (`service_station_id`)
    REFERENCES `mydb`.`Service_stations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Stations_has_Cars_Cars1`
    FOREIGN KEY (`car_id`)
    REFERENCES `mydb`.`Cars` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Orders_Car_Services1`
    FOREIGN KEY (`car_services_id`)
    REFERENCES `mydb`.`Car_services` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_orders_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Models_parts_compatibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Models_parts_compatibility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand_model_id` INT NOT NULL,
  `car_part_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Brand_Models_has_Car_Parts_Car_Parts1_idx` (`car_part_id` ASC),
  INDEX `fk_Brand_Models_has_Car_Parts_Brand_Models1_idx` (`brand_model_id` ASC),
  CONSTRAINT `fk_Brand_Models_has_Car_Parts_Brand_Models1`
    FOREIGN KEY (`brand_model_id`)
    REFERENCES `mydb`.`Brand_models` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Brand_Models_has_Car_Parts_Car_Parts1`
    FOREIGN KEY (`car_part_id`)
    REFERENCES `mydb`.`Car_parts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
